### ISSUE TITLE
Error importing QVariant with PySide6 (hdf5view/models.py)

### ISSUE THREAD

**Issue by tgwoodcock** [marts/hdf5view#13]
Testing hdf5view 0.1.1 with Python 3.12.2 and PySide6 resulted in the following import error with QVariant in hdf5view/models.py:

```
>>> import subprocess
>>> subprocess.run("hdf5view", capture_output=True)
CompletedProcess(args='hdf5view', returncode=1, stdout=b'', stderr=b'Traceback (most recent call last):\r\n  File "<frozen runpy>", line 198, in _run_module_as_main\r\n  File "<frozen runpy>", line 88, in _run_code\r\n  File "D:\\Work\\test_hdf5view\\Scripts\\hdf5view.exe\\__main__.py", line 4, in <module>\r\n  File "D:\\Work\\test_hdf5view\\Lib\\site-packages\\hdf5view\\main.py", line 30, in <module>\r\n    from .mainwindow import MainWindow\r\n  File "D:\\Work\\test_hdf5view\\Lib\\site-packages\\hdf5view\\mainwindow.py", line 28, in <module>\r\n    from .views import HDF5Widget\r\n  File "D:\\Work\\test_hdf5view\\Lib\\site-packages\\hdf5view\\views.py", line 37, in <module>\r\n    from .models import (\r\n  File "D:\\Work\\test_hdf5view\\Lib\\site-packages\\hdf5view\\models.py", line 10, in <module>\r\n    from qtpy.QtCore import (\r\nImportError: cannot import name \'QVariant\' from \'qtpy.QtCore\' (D:\\Work\\test_hdf5view\\Lib\\site-packages\\qtpy\\QtCore.py)\r\n')
```

It seems from the [PySide6 docs](https://doc.qt.io/qtforpython-6/considerations.html#qvariant) that QVariant has been removed and needs to be handled differently.

Need to check if this is handled by QtPy or whether we need to write a workaround for PySide6.

Test was done with:

- h5py      3.11.0
- hdf5view  0.1.1
- numpy     2.1.1
- packaging 24.1
- pip       24.2
- psutil    6.0.0
- pyqtgraph 0.13.7
- PySide6            6.7.2
- PySide6_Addons     6.7.2
- PySide6_Essentials 6.7.2
- QtPy               2.4.1
- shiboken6          6.7.2

The error did not occur with PyQt5 or PyQt6 (PySide2 is not available for Python >= 11).

**Comment by tgwoodcock** [comment]
The two cases where `QVariant` appears in hdf5view/models.py are in the `ImageModel` and `PlotModel` classes, which are subclasses of `QAbstractItemModel`. The function `self.data()` must be implemented for subclassing but is not needed for either `ImageModel` or `PlotModel` and so an invalid `QVariant` was returned by `self.data()` in these cases, as advised by the documentation.

Now that the function `QVariant()` appears to have been removed and the Qt6 docs advise against using it in future code, the [PySide6 docs](https://doc.qt.io/qtforpython-6/considerations.html#qvariant) mention that Python objects can be used instead and that `None` is an invalid `QVariant`. 

The solution to the import error appears to be to remove the import `QVariant` and to return `None` in `ImageModel.data()` and `PlotModel.data()`. This has been tested with 
- PyQt5 5.15.11, 
- PyQt6 6.7.1 and 
- PySide6 6.7.2 with 
- QtPy 2.4.1

and works fine for all of these.
