### ISSUE TITLE
HDF5 External links are not supported

### ISSUE THREAD

**Issue by Lgt2x** [marts/hdf5view#8]
Using the following h5py script to create data using external links :

```python
import h5py
import numpy as np

file1 = h5py.File('test_a.hdf5', 'w')
file1['/path/to/data'] = np.array([0,1,2])
file1.close()

file2 = h5py.File('test_b.hdf5', 'w')
file2['/path/to/data2'] = np.array([3,4,5])
file2.close()

composite = h5py.File('test.hdf5', 'w')
composite['/a'] = h5py.ExternalLink('test_a.hdf5', '/path/to/data')
composite['/b'] = h5py.ExternalLink('test_b.hdf5', '/path/to/data2')
composite.close()
```

`h5dump` can open the `test.hdf5` dataset:
```
HDF5 "test.hdf5" {
GROUP "/" {
   EXTERNAL_LINK "a" {
      TARGETFILE "test_a.hdf5"
      TARGETPATH "/path/to/data"
         DATASET "/path/to/data" {
            DATATYPE  H5T_STD_I64LE
            DATASPACE  SIMPLE { ( 3 ) / ( 3 ) }
            DATA {
            (0): 0, 1, 2
            }
         }
   }
   EXTERNAL_LINK "b" {
      TARGETFILE "test_b.hdf5"
      TARGETPATH "/path/to/data2"
         DATASET "/path/to/data2" {
            DATATYPE  H5T_STD_I64LE
            DATASPACE  SIMPLE { ( 3 ) / ( 3 ) }
            DATA {
            (0): 3, 4, 5
            }
         }
   }
}
}
```

but `hdf5view` cannot:
```
Traceback (most recent call last):
  File ".../hdf5view/models.py", line 91, in handle_expanded
    child_node = self.hdf[path]
                 ~~~~~~~~^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File ".../h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 189, in h5py.h5o.open
KeyError: 'Unable to synchronously open object (component not found)'
```

External links are documented here in [h5py](https://docs.h5py.org/en/stable/high/group.html#external-links)

**Comment by tgwoodcock** [comment]
Hi @Lgt2x , many thanks for pointing this out and for your PR. It looks good and I'll look into it in detail and get back to you hopefully towards the end of next week.

**Comment by tgwoodcock** [comment]
Thanks for your contribution, @Lgt2x! I tested the changes with some more complex data including with the image tab, slice and attributes tables and everything works fine. 👍
